<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PimaxVrcSupervisor.UpdateCheckTestHelper</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.AccessControl" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\PimaxVrcSupervisor\UpdateCheckExclusion.cs" Link="UpdateCheckExclusion.cs" />
  </ItemGroup>

</Project>
